name: PortalStick
main: com.matejdro.bukkit.portalstick.PortalStick
version: 3.0.9999
authors: [matejdro, oliverw92, V10lator]
commands:
  portalstick:
    description: Aperture Science Portal Stick
    aliases: portal
    usage: /<command> help
